name: deliverynotifications
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.13.1
  webview_flutter_wkwebview: ^3.10.0
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  onesignal_flutter: ^5.1.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  image_picker: ^0.8.7
  file_picker: ^5.2.10
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.6
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Add this section to override problematic dependencies
dependency_overrides:
  win32: ^3.1.4
  collection: ^1.17.0

flutter:
  uses-material-design: true
