name: deliverynotifications
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.13.1
  webview_flutter_wkwebview: ^3.10.0
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  onesignal_flutter: ^5.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^0.8.9
  file_picker: ^5.3.1
  permission_handler: ^10.4.5
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
